### PR TITLE
Next release

### PR DESCRIPTION
**Pull request by ryshu**
- Revert the rename of novu to novu-python
- Upgrade dev deps to latest available
- add a Makefile
- Start a contribution guideline for the projet

### CODE REVIEW

**Review by unicodeveloper — APPROVED** [review]

**Comment by unicodeveloper** [comment]
Hey @ryshu I just did the following..

- I followed your setup and created a new temporary token in the new novu account on PyPi
- I updated it on this repository.
- I ran CI/CD on the v1.10 release tag and got this error:

Screenshot 2023-04-11 at 07 53 47

Am I running the CI/CD the wrong way? What am I missing?

**Comment by unicodeveloper** [comment]
@ryshu Is there a way for us to communicate better and faster in real time? That way we can fix this immediately

**Comment by ryshu** [comment]
Hi @unicodeveloper, 

I think you're stuck here because you're trying to republish a version that already exists in PyPi and you don't own their POS.

If we want to test your setup, we can more simply use the "alpha" branch by doing a pre-release of the "novu" package instead of the "novu-python" package as the CI/CD does if we read it in detail.

To quickly move on the subject, I think we should do a pre-release on alpha.
I changed the branch to go directly to the latter.

**Pull request merged**
