### PR TITLE
ALPHA: Next RELEASE

### PR DESCRIPTION
**Pull request by ryshu**

### CODE REVIEW

**Comment by ryshu** [comment]
@unicodeveloper Seem that we got 2 problems on the setup:

codecov doesn't seem to be setup for code coverage https://github.com/novuhq/novu-python/actions/runs/4686037852/jobs/8303702899?pr=22 

Something isn't right with the publish tags job  https://github.com/novuhq/novu-python/actions/runs/4686037846/jobs/8303702862?pr=22

I take a look at the second, but can you handle codecov setup on your side ?

**Comment by ryshu** [comment]
@unicodeveloper Ok, for semver tag it seem that my previously created token is still used in SEMENTIC_RELEASE_BOT https://github.com/novuhq/novu-python/actions/runs/4686236681/jobs/8304101029

I follow instruction their instruction here to solve the problem, but we still need a fresh token because my doesn't work anymore https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch

**Comment by unicodeveloper** [comment]
@ryshu Catching up on this now. 

1. I need to set up codecov
2. I need to update the token for SEMANTIC_RELEASE_BOT

correct?

**Comment by unicodeveloper** [comment]
@ryshu I just updated the codecov token

**Comment by ryshu** [comment]
> @ryshu I just updated the codecov token

Working for coverage https://github.com/novuhq/novu-python/actions/runs/4686236688/jobs/8306798208

**Comment by unicodeveloper** [comment]
@ryshu I just updated the token for SEMANTIC release.

**Comment by ryshu** [comment]
@unicodeveloper Ok for me, as you can see CI auto publish a new commit (https://github.com/novuhq/novu-python/pull/22/commits/7c42a3abf0e050548e34d867a067b7a0e61bab6a) with the changelog and push it on pypi: https://pypi.org/project/novu/

You can also see that it's flagged as a pre-release in the available version (that is what we want, only volunteer developers will download it) https://pypi.org/project/novu/#history

**Comment by ryshu** [comment]
For me, it can be released for the first version.

Readthedocs will auto update related documentation and badges will be updated using new repositories (see https://github.com/novuhq/novu-python/tree/alpha for examples)

**Comment by unicodeveloper** [comment]
Awesome. Getting the hang of it now. Thanks

**Comment by ryshu** [comment]
> One more question. If I approve, and this is merged into main..
> 
> 1. We will tag a new release here on GitHub
> 2. Once we tag a new release, it will automatically release it on PyPi
> 
> Correct? @ryshu

Yes, + auto-publish of docs and coverage report

**Comment by unicodeveloper** [comment]
Perfecto!

Okay will merge now @ryshu

**Review by unicodeveloper — APPROVED** [review]

**Comment by ryshu** [comment]
@unicodeveloper Oups, I forgot to mention that you should not squash the commits. The idea is to keep all the history so that the bot generates the changelog.

**Comment by unicodeveloper** [comment]
Oh I did not know that. So what do we do?

**Comment by ryshu** [comment]
I can create a "fake" commit with right name in order to trigger release

**Comment by unicodeveloper** [comment]
Okay, let's do that @ryshu . Please go ahead.

**Pull request merged**
