### PR TITLE
docs : update bug_report.md

### PR DESCRIPTION
**Pull request by HarshMN2345**
In the improved bug report, I've made several enhancements to provide a more detailed and structured description of the issue. Here's a summary of the changes:

Clear and Concise Description:

The description of the bug is clearer and more concise, stating that the current implementation has a bug causing unexpected behavior. Detailed Steps to Reproduce:

The steps to reproduce the bug are provided in a numbered list, making it easy to follow and understand. Expected Behavior:

There's a specific section explaining what the user or reporter expected to happen when performing the steps. Screenshots:

There's a placeholder for attaching relevant screenshots, if available. Screenshots can provide visual context for better understanding. Versions Information:

There's a section for specifying the versions of relevant software or libraries. This helps in reproducing the bug and understanding potential compatibility issues. Additional Context:

There's a section for providing any extra information or context about the problem. This can include specific conditions, error messages, or related background information. Note to Reviewers:

A note is added for reviewers to guide them on what to focus on when investigating the bug report. These improvements aim to make the bug report more informative, structured, and actionable. This can lead to quicker and more accurate resolutions for the reported issue.

### CODE REVIEW

**Review by Cliftonz — APPROVED** [review]

**Comment by Cliftonz** [comment]
@HarshMN2345 Looks like a CI failed, once you have it fixed let me know and we can continue merging this in.

**Comment by HarshMN2345** [comment]
> @HarshMN2345 Looks like a CI failed, once you have it fixed let me know and we can continue merging this in.

Can you explain what that means and can you provide me with something so that i can solve it myself

**Comment by Cliftonz** [comment]
Looks like there is something spelled wrong.
CleanShot 2023-10-03 at 11 59 07@2x
Though I am not sure, if you run pre-commit locally it should tell you what is going on.

**Comment by ryshu** [comment]
> Looks like there is something spelled wrong. CleanShot 2023-10-03 at 11 59 07@2x Though I am not sure, if you run pre-commit locally it should tell you what is going on.

Hmm, doesn't seem to be related to your development.

I will update the codespell configuration so that this no longer happens because it is a typo in one of the commits of the repository which must have caused this problem

**Comment by ryshu** [comment]
@HarshMN2345 Everything should be fine if you rebase on the last alpha commit.

Please take care to rename your commit following the contribution guidelines: https://github.com/novuhq/novu-python/blob/main/CONTRIBUTING.rst

This should give you a commit named like "docs : update bug_report.md"

**Comment by HarshMN2345** [comment]
@ryshu hey i have changed the name to docs : update bug_report.md

**Comment by Cliftonz** [comment]
@HarshMN2345 Looks like you still need to rebase, have you done that yet?

**Comment by HarshMN2345** [comment]
@Cliftonz done

**Pull request merged**
