### PR TITLE
ALPHA: Next Release

### PR DESCRIPTION
**Pull request by ryshu**

### CODE REVIEW

**Comment by ryshu** [comment]
FYI @unicodeveloper @Cliftonz @scopsy 

Using the renovate bot, I ran all the updates that were available for both the production environment and the development utilities.

We should have automatic MRs from renovate to offer us the security patch quickly and avoid having to manage everything by dependabot for once.

**Comment by Cliftonz** [comment]
@ryshu what else needs done to this PR?

**Comment by ryshu** [comment]
> @ryshu what else needs done to this PR?

I don't really understand the question here

We don't have a Roadmap in this depot so there isn't really anything left to do to deliver.

**Comment by Cliftonz** [comment]
> > @ryshu what else needs done to this PR?
> 
> I don't really understand the question here
> 
> We don't have a Roadmap in this depot so there isn't really anything left to do to deliver.

So you just need an approval correct?

**Comment by ryshu** [comment]
> > > @ryshu what else needs done to this PR?
> > 
> > 
> > I don't really understand the question here
> > We don't have a Roadmap in this depot so there isn't really anything left to do to deliver.
> 
> So you just need an approval correct?

Seems good to me to publish these changes.

For the future, if you want to see things a little more clearly I think you [Novu] need to define targets (via projects?).
With defined targets, I can help you achieve them technically and set deadlines / ensure good execution / develop functionalities.

Currently, it's more of a continuous flow

**Review by Cliftonz — APPROVED** [review]

**Comment by ryshu** [comment]
@Cliftonz FYI, given that you squashed all the commits rather than a "Rebase and Merge", there will be no automatic release.

**Comment by Cliftonz** [comment]
@ryshu crap, do I need to automatically run a pipeline then?

**Comment by ryshu** [comment]
> @ryshu crap, do I need to automatically run a pipeline then?

Nah, I'm going to rewrite the history manually by deleting the commit and pushing the commits from the alpha branch

**Pull request merged**
