### PR TITLE
feat: add exponential retry mechanism

### LINKED ISSUE #91: Add Exponential Retry Mechanism with Idempotency Headers
In order to enhance the resilience and reliability of our SDK, we would like to introduce an Exponential Retry mechanism for retrying failed requests. Additionally, to ensure the idempotent processing of requests, it's vital to incorporate support for providing an Idempotency Key as per the draft specified in the [HTTP Idempotency Key Header Field](https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/).

The key requirements for this implementation include:

1. **Exponential Retry Mechanism**:
   - The SDK should retry failed requests following an exponential backoff strategy to minimize the contention and impact on the systems involved.
   - The SDK should ensure that the retry mechanism is configurable (e.g., max retries, initial delay, maximum delay).

2. **Idempotency Key Provisioning**:
   - The SDK should allow for either automatic or manual provisioning of an Idempotency Key for each request.
   - The Idempotency Key should conform to either CUID, ULID, or UUID formats as specified in the draft.
   - The Idempotency Key should be included in the HTTP Header as `Idempotency-Key` and following the standards outlined in the draft.

3. **Configuration and Documentation**:
   - The SDK should provide configuration options for enabling/disabling the Exponential Retry mechanism and Idempotency Key provisioning.
   - Comprehensive documentation should be provided explaining the configuration options, operational behavior, and the benefits of using the Exponential Retry mechanism along with Idempotency Keys.

Acceptance Criteria:

- [ ] Implementation of the Exponential Retry mechanism with configurable parameters.
- [ ] Provisioning of Idempotency Keys, either automatically or manually, conforming to specified formats (CUID, ULID, or UUID).
- [ ] Adequate unit and integration testing to ensure the robustness and reliability of the implemented features.
- [ ] Comprehensive documentation on the usage and configuration of the Exponential Retry mechanism and Idempotency Key provisioning.
- [ ] Adherence to the specifications outlined in the [HTTP Idempotency Key Header Field draft](https://datatracker.ietf.org/doc/draft-ietf-httpapi-idempotency-key-header/).

Please refer to the draft for further details on the HTTP Idempotency Key Header Field and ensure adherence to the specified standards while implementing this feature in the SDK.

### PR DESCRIPTION
**Pull request by im-perativa**
closes #91  

This PR

- [x] Adds HTTP Exponential Retry mechanism to novu client
- [x] Adds relevant tests
- [x] Adds UUID based Idempotency Headers
- [x] Update docs
- [x] Can be used with existing custom `requests.Session`
- [x] Refer to the go-lang library to keep the method signature and configuration the same

Sample usage: 
```python
from novu.api import EnvironmentApi
from novu.api.base import RetryConfig

url = "https://api.novu.co"
api_key = "<API_KEY>"

# # List existing environments
novu = EnvironmentApi(
    url, api_key, retry_config=RetryConfig(initial_delay=1, wait_min=2, wait_max=100, retry_max=4)
).list()

```

### CODE REVIEW

**Review by ryshu — CHANGES_REQUESTED** [review]
I haven't looked in detail but it seems good to me in terms of functionality.

On the other hand, I am against adding a new dependency for clients while these functionalities already exist in the library that we use. See the following links:

* https://docs.python-requests.org/en/latest/user/advanced/#example-automatic-retries
* https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry

**Comment by im-perativa** [comment]
> I haven't looked in detail but it seems good to me in terms of functionality.
> 
> On the other hand, I am against adding a new dependency for clients while these functionalities already exist in the library that we use. See the following links:
> 
>     * https://docs.python-requests.org/en/latest/user/advanced/#example-automatic-retries
> 
>     * https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry

Thanks for the feedback @ryshu . I was about to use the `requests` + urllib3 `Retry` before but as mentioned [here](https://github.com/novuhq/novu-python/issues/91#issuecomment-1762905908) I realized it would interfere/confusing for the already provided custom session options (only in python SDK) .

Afaik, they also provide less customization / parameters so it will make the configuration differ from the existing method in go SDK.
Would that be okay?

**Comment by ryshu** [comment]
> > I haven't looked in detail but it seems good to me in terms of functionality.
> > On the other hand, I am against adding a new dependency for clients while these functionalities already exist in the library that we use. See the following links:
> > ```
> > * https://docs.python-requests.org/en/latest/user/advanced/#example-automatic-retries
> > 
> > * https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry
> > ```
> 
> Thanks for the feedback @ryshu . I was about to use the `requests` + urllib3 `Retry` before but as mentioned [here](https://github.com/novuhq/novu-python/issues/91#issuecomment-1762905908) I realized it would interfere/confusing for the already provided custom session options (only in python SDK) .
> 
> Afaik, they also provide less customization / parameters so it will make the configuration differ from the existing method in go SDK. Would that be okay?

For me, this is precisely what is interesting:

* if someone provides a session, we do nothing here (apart from offering them our retry configuration in the documentation)
* if no one provided session, we default initialization with retry configuration (to apply exponential retry on every SDK by default)

For me, there is no problem with the fact that we do not have all the functionalities of the GO lib as long as the behavior (exponential retry via the `backoff_factor`) is well implemented so as not to retry too often on the server.

WDYT @Cliftonz ?

**Comment by im-perativa** [comment]
I would like to know your opinion before changing this pr @Cliftonz

**Comment by Cliftonz** [comment]
@im-perativa  I agree with ryshu the backoff strategy is important.

I do want to specify that by default retry should not be on, as we want users to specifically opt into this and it changes the priority from availability to consistency.

@ryshu  what features are you not able to do 1:1?

**Comment by ryshu** [comment]
Ok for the opt-in instead off opt-out.

@im-perativa Can you clarify the missing functionnality implemented in go sdk ?

**Comment by unicodeveloper** [comment]
Please, how can we move forward here? @ryshu

**Comment by ryshu** [comment]
> Please, how can we move forward here? @ryshu

Hi @unicodeveloper,

Reply pending from @im-perativa in fact

**Comment by im-perativa** [comment]
@ryshu Sorry I'm not sure if I will have the capacity to modify it in timely manner so that no external dependencies is added, nor do I think it will be an elegant solution. Feel free to reassign the issue or modify it

**Pull request closed without merging**
