### PR TITLE
ALPHA: Next release

### PR DESCRIPTION
**Pull request by ryshu**

### CODE REVIEW

**Comment by ryshu** [comment]
@unicodeveloper Hi, ok for me to publish new release

**Comment by ryshu** [comment]
Hi @unicodeveloper ,

Can we merge ?

**Comment by ryshu** [comment]
Coverage can be ignored until https://github.com/codecov/codecov-action/issues/1262 is solved

**Comment by ryshu** [comment]
Hi @unicodeveloper , I will take a look at https://github.com/novuhq/novu-python/issues/221 after this PR is merged

**Comment by unicodeveloper** [comment]
> Hi @unicodeveloper , I will take a look at #221 after this PR is merged

Thank you very much @ryshu

**Pull request merged**
