### PR TITLE
ALPHA: Next RELEASE

### PR DESCRIPTION
**Pull request by ryshu**

### CODE REVIEW

**Comment by ryshu** [comment]
@unicodeveloper @Cliftonz Hi,

Pending an approval to release 2 bugfixs from @cherfia and @danbim

**Comment by Cliftonz** [comment]
@ryshu Do we need to worry about the failing test?

**Comment by ryshu** [comment]
Nope, coverage don't work some Times

**Review by Cliftonz — APPROVED** [review]

**Pull request merged**
