### PR TITLE
fix: #148 make webhook_url and channel optional in SubscriberChannelSettingsCredentialsDto

### PR DESCRIPTION
**Pull request by danbim**
Fix for https://github.com/novuhq/novu-python/issues/148

### CODE REVIEW

**Review by ryshu — APPROVED** [review]
LGTM

**Comment by danbim** [comment]
@ryshu Thx! If possible, could you do a patch release soon? The bug blocks my development / feature rollout currently :)

**Comment by danbim** [comment]
Oh, I see failures. I'll fix them ASAP.

**Comment by ryshu** [comment]
@danbim Yup, no problem. Will be included with the other fix

**Pull request merged**
